# Generated by Django 4.2 on 2023-05-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceo',
            name='pohlavi',
            field=models.CharField(choices=[('muž', 'Muž'), ('žena', 'Žena')], help_text='Vyberte pohlaví', max_length=10, verbose_name='Pohlaví'),
        ),
    ]
