# Generated by Django 4.2 on 2023-06-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_skupina_zkratka_nazev'),
    ]

    operations = [
        migrations.AddField(
            model_name='skupina',
            name='fotka',
            field=models.ImageField(blank=True, help_text='Nahrajte fotku skupiny', null=True, upload_to='skupiny', verbose_name='Fotka kpop skupiny'),
        ),
    ]
