# Generated by Django 4.2 on 2023-06-15 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_spolecnost_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clen',
            options={'ordering': ['prijmeni', 'jmeno'], 'verbose_name': 'Clen', 'verbose_name_plural': 'Clenové'},
        ),
    ]
